### ISSUE TITLE
vapor binary expects OpenSSL in hardcoded path

### ISSUE THREAD

**Issue by herzi** [vapor/homebrew-tap#19] opened 2018-12-07 08:27 UTC
I have set up homebrew to use a different path than `/usr/local`. After I installed vapor, it does not work and fails with this error:

    # vapor --help
    dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
      Referenced from: /Users/herzi/.brew/bin/vapor
      Reason: image not found
    Abort trap: 6
    #

**Comment by twof** [comment] 2018-12-07 13:30
Have you installed openssl? If so, @calebkleveter might be able to help. They had a similar looking problem with Ether, but I'm not sure how they fixed it.

**Comment by calebkleveter** [comment] 2018-12-07 13:50
And if you have already installed OpenSSL, try updating it.

**Comment by herzi** [comment] 2018-12-07 14:12
OpenSSL is installed and updated. Also, the problem is not missing OpenSSL, it's using the wrong path to the library (which seems to be hardcoded somewhere).

OpenSSL is located at `/Users/herzi/.brew/opt/openssl/lib/libssl.1.0.0.dylib` (within `brew --prefix`) but vapor is looking for it in the wrong location.

**Comment by calebkleveter** [comment] 2018-12-07 14:17
@herzi What OpenSSL version are you on?

**Comment by calebkleveter** [comment] 2018-12-07 14:18
@tanner0101 I think that can be fixed by re-compiling the executable with an updated version of OpenSSL and publishing that.

**Comment by herzi** [comment] 2018-12-07 15:00
@calebkleveter 

```
# brew info openssl
openssl: stable 1.0.2q [keg-only]
SSL/TLS cryptography library
https://openssl.org/
…
/Users/herzi/.brew/Cellar/openssl/1.0.2q (1,787 files, 12MB)
  Built from source on 2018-12-07 at 09:23:56
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl.rb
…
```

(Yes, I updated a couple of minutes before starting to file this bug report.)

**Comment by calebkleveter** [comment] 2018-12-07 15:19
Right, looks like the issue is what I suspected. Vapor Toolbox expects a different version of OpenSSL and can't find it. That's why I suggested the fix I did to Tanner.

**Comment by twof** [comment] 2018-12-07 15:26
@herzi Do you also have macports installed? That can sometimes cause issues. It could also be that you have two different versions of openSSL installed with HomeBrew so check what you have installed.

**Comment by herzi** [comment] 2018-12-07 15:26
A different version? To me this looks like its just looking at the wrong place.

To summarize:
1. vapor is looking for `/usr/local/opt/openssl/lib/libssl.1.0.0.dylib` (which does not exist)
2. There is OpenSSL 1.0.2q at `/Users/herzi/.brew/opt/openssl/lib/libssl.1.0.0.dylib` (installed with brew).
3. It's caused by the vapor module in home-brew not honoring brew's prefix.

**Comment by herzi** [comment] 2018-12-07 15:27
@twof No macports here. For years.

The problem seems to be `brew --prefix`, which is not honored by the vapor binary.

**Comment by twof** [comment] 2018-12-07 15:29
oh shoot my bad. macports installs stuff at `/opt/local/bin` not `/usr/local/opt`.

**Comment by grundoon** [comment] 2018-12-07 18:23
You should likely either have `brew` installed for all users (not in a home subdirectory) or create a symlink at the expected location to the installed (e.g. `ln -s /user/local/opt/openssl /Users/herzi/.brew/opt/openssl` or whatever the correct command would be). Note that I have _not_ actually tested whether the symlink approach would work properly.

**Comment by herzi** [comment] 2018-12-07 21:29
The whole point of installing homebrew into the home directory is to avoid messing with other users' configurations. This is a supported setup of homebrew. While a symlink would certainly work around this issue, it doesn't solve it.

IMO, the solution would be to support what brew supports (i.e. `brew --prefix` ≠ `/usr/local`).

**Comment by vzsg** [comment] 2018-12-07 22:49
The actual problem that breaks the toolbox on your system is that it links the shared libraries by absolute path. (This is the default behavior of SPM, by the way.)

To solve this, the references need to be manually overwritten using `install_name_tool` – loading the two OpenSSL packages via `@rpath` would probably work wherever your Homebrew prefix is.

Of course, this should be done before the binary is distributed on Homebrew.

**Comment by grundoon** [comment] 2018-12-07 22:50
I believe all SSL services in Vapor 3 are provided through NIO – https://github.com/apple/swift-nio-ssl (or  swift-nio-transport-services on Network.framework), and that's where you'd be looking for this type of configuration support. But I'm hardly an expert on the architecture and leave it to @tanner0101 or others more intimately familiar for comment.

(ah right... vzsg finally drills it into my head that you're talking just toolbox at this point)

**Comment by 0xTim** [comment] 2020-10-12 12:44
Closing due to inactivity. OpenSSL is no longer a requirement of Vapor as well

**Closed as completed by 0xTim** 2020-10-12 12:44 UTC
